pin cnvpytor to 1.3.1 to resolve AttributeError: 'PosixPath' object has no attribute 'split'
(cherry picked from commit 8a1e09d42fbe13f3d4adca517338d08d1352003b)